# Generated by Django 3.1.1 on 2020-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='releaseTitle',
            field=models.CharField(default='noTitle', max_length=500),
        ),
    ]
