# Generated by Django 3.1.1 on 2020-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_release_releasetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='releaseArtist',
            field=models.CharField(default='noArtists', max_length=500),
        ),
    ]
