# Generated by Django 3.1.1 on 2020-10-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link_text',
            field=models.CharField(max_length=1000),
        ),
    ]
